### ISSUE TITLE
Couldn't find pthreadGC2.dll for this platform windows/x86_64

### ISSUE THREAD

**Issue by liuyangedu** [libpd/puredatap5#15]
I pull the code from tag 0.10.0 and build it in win10_x86_64 using mingw32

`mingw32-make UTIL=true EXTRA=true javalib`

and try to run the java sample in https://github.com/libpd/libpd/tree/master/samples/java/com/noisepages/nettoyeur/libpd/sample

I open eclipse, new a project and add the libpd.jar I compiled and run.

error:

`
Exception in thread "main" org.puredata.core.NativeLoader$NativeLibraryLoadError: Couldn't find pthreadGC2.dll for this platform windows/x86_64
	at org.puredata.core.NativeLoader.loadLibraryFromJar(NativeLoader.java:113)
	at org.puredata.core.NativeLoader.loadLibrary(NativeLoader.java:100)
	at org.puredata.core.NativeLoader.loadLibrary(NativeLoader.java:91)
	at org.puredata.core.PdBase.<clinit>(PdBase.java:76)
	at com.noisepages.nettoyeur.libpd.sample.JavaSoundThread.<init>(JavaSoundThread.java:44)
	at com.noisepages.nettoyeur.libpd.sample.JavaSoundSample.main(JavaSoundSample.java:24)
`

**Comment by b2renger** [comment]
@karon1988edu 

There's an issue with the packed windows native that has been hanging around for some time. The solution is referenced here : https://github.com/libpd/libpd/issues/155

You would need to build it yourself, or you can try to grab them here : https://github.com/mgsx-dev/gdx-pd/tree/master/native/libs

rename them and replace them in the library you downloaded. Those have been compiled according to the issues referenced before

I'm not sure it works, I don't have a windows machine at hand to test and make a pull request yet
